# fly.toml app configuration file generated for lingering-lake-6285 on 2023-05-21T00:28:12+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lingering-lake-6285"
primary_region = "hkg"

[env]
  PORT = "3000" # add this

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
